FROM keymetrics/pm2:14-alpine
RUN ls
# Bundle APP files

WORKDIR /usr/src/app
COPY ./backend/src src/
COPY ./backend/package.json .
COPY ./backend/pm2.json .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn

RUN npm install

# Show current folder structure in logs
RUN ls -al -R

CMD [ "pm2-runtime", "start", "pm2.json", "--env", "development"]
